feat: restore FS

diff --git a/stacks/dhis2-core/helmfile.yaml b/stacks/dhis2-core/helmfile.yaml
--- a/stacks/dhis2-core/helmfile.yaml
+++ b/stacks/dhis2-core/helmfile.yaml
@@ -103,6 +103,73 @@ releases:
           rootPassword: dhisdhis
           forcePassword: true
       - defaultBuckets: dhis2
+      - sidecars:
+          - name: "{{ requiredEnv "INSTANCE_NAME" }}-minio-seed"
+            image: bitnami/minio:latest
+            version: "{{ requiredEnv "MINIO_CHART_VERSION" }}"
+            pullPolicy: {{ requiredEnv "IMAGE_PULL_POLICY" }}
+            env:
+              - name: HOSTNAME
+                value: {{ requiredEnv "HOSTNAME" }}
+              - name: DATABASE_ID
+                value: "{{ requiredEnv "DATABASE_ID" }}"
+              - name: IM_ACCESS_TOKEN
+                value: {{ requiredEnv "IM_ACCESS_TOKEN" }}
+            command:
+              - "/bin/bash"
+              - "-c"
+              - |
+                # Wait for MinIO to be ready
+                # TODO: add a timeout here so it doesn't hang forever
+                until curl --silent --fail http://{{ requiredEnv "INSTANCE_NAME" }}-minio:9000/minio/health/live; do
+                  echo "Waiting for MinIO to be ready..."
+                  sleep 2
+                done
+                # TODO: Shouldn't be necessary, but it seems like the pod is not ready despite the above
+                sleep 10
+                echo "MinIO is ready!!!"
+                
+                mc alias set myminio http://{{ requiredEnv "INSTANCE_NAME" }}-minio:9000 dhisdhis dhisdhis
+                
+                seed_file=myminio/dhis2/seeded.txt
+                if mc stat $seed_file >/dev/null 2>&1; then
+                  echo "Already seeded, skipping..."
+                else
+                  DATABASE_URL="$HOSTNAME/databases/$DATABASE_ID"
+                  echo "DATABASE_URL: $DATABASE_URL"
+                  #FILESTORE_ID=$(curl --connect-timeout 10 --retry 5 --retry-delay 1 --fail -L $DATABASE_URL --cookie "accessToken=$IM_ACCESS_TOKEN" | jq -r '.filestoreId')
+                  FILESTORE_OUTPUT=$(curl --connect-timeout 10 --retry 5 --retry-delay 1 --fail -L $DATABASE_URL --cookie "accessToken=$IM_ACCESS_TOKEN")
+                  echo "FILESTORE_OUTPUT: $FILESTORE_OUTPUT"
+                  FILESTORE_ID=$(echo "$FILESTORE_OUTPUT" | jq -r '.filestoreId')
+                  echo "FILESTORE_ID: $FILESTORE_ID"
+                  if [[ -z "$FILESTORE_ID" ]]; then
+                    echo "No filestore id associated with database"
+                  else
+                    echo "Seeding..."
+                    
+                    tmp_file=$(mktemp)
+                    trap 'rm -f "$tmp_file"' EXIT  # Ensures cleanup on script exit
+                    FILESTORE_DOWNLOAD_URL="$HOSTNAME/databases/$FILESTORE_ID/download"
+                    curl --connect-timeout 10 --retry 5 --retry-delay 1 --fail -L "$FILESTORE_DOWNLOAD_URL" --cookie "accessToken=$IM_ACCESS_TOKEN" > "$tmp_file"
+                    
+                    tmp_dir=$(mktemp -d /tmp/minio.XXXXXX)
+                    trap 'rm -rf "$tmp_dir"' EXIT  # Ensures cleanup on script exit
+                    gunzip -c "$tmp_file" | tar xf - -C "$tmp_dir"
+                    
+                    mc cp --recursive "$tmp_dir"/* myminio/dhis2
+                    
+                    echo "Seeded from $FILESTORE_DOWNLOAD_URL" | mc pipe $seed_file
+                    
+                    # Clean up            
+                    rm -f "$tmp_file"
+                    rm -rf "$tmp_dir"
+                    
+                    echo "Done seeding!"
+                  fi
+                fi
+
+                # Wait forever
+                tail -f /dev/null
   {{- end }}
 
 repositories:
